using Common.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEulerSolutions.Solutions
{
    public class Solution2
    {
        /// <summary>
        /// Even Fibonacci numbers
        /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        /// By starting with 1 and 2, the first 10 terms will be:
        /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        /// By considering the terms in the Fibonacci sequence whose values 
        /// do not exceed four million, find the sum of the even-valued terms.
        /// </summary>
        public static void Solve()
        {
            int uLimit = 4000000;
            int i = 1;
            int j = 2;
            int next = 0;
            List<int> lstEvenNumbers = new() { j };
            while (next < uLimit)
            {
                next = i + j;
                i = j;
                j = next;
                if (next % 2 == 0) lstEvenNumbers.Add(next);
            }
            Console.WriteLine(MathHelper.GetTotal(lstEvenNumbers));
        }
    }
}
